# Generated by Django 4.2.23 on 2025-11-25
from django.db import migrations


def seed_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("emails", "EmailTemplate")

    signup_otp_tpl, _ = EmailTemplate.objects.update_or_create(
        name="signup_otp",
        defaults={
            "subject": "Your POS signup code",
            "html_body": """
                <p>Hello,</p>
                <p>Your signup code is <strong>{{ code }}</strong>.</p>
                <p>It expires in {{ expires_minutes }} minutes.</p>
                <p>If you did not request this, you can ignore this email.</p>
            """,
            "locale": "en",
            "version": 1,
            "is_active": True,
        },
    )

    welcome_tpl, _ = EmailTemplate.objects.update_or_create(
        name="welcome_tenant",
        defaults={
            "subject": "Welcome to the POS platform",
            "html_body": """
                <p>Welcome!</p>
                <p>Your tenant <strong>{{ tenant_name }}</strong> has been created.</p>
                <p>You can now sign in and continue onboarding.</p>
            """,
            "locale": "en",
            "version": 1,
            "is_active": True,
        },
    )


def unseed_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("emails", "EmailTemplate")
    EmailTemplate.objects.filter(name__in=["signup_otp", "welcome_tenant"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_email_templates, unseed_email_templates),
    ]
