# Generated by Django 4.2.23 on 2025-11-25
from django.db import migrations


def update_welcome_template(apps, schema_editor):
    EmailTemplate = apps.get_model("emails", "EmailTemplate")
    EmailTemplate.objects.update_or_create(
        name="welcome_tenant",
        defaults={
            "subject": "Welcome to your POS workspace",
            "html_body": """
                <div style="font-family: Arial, sans-serif; color: #111; padding: 16px;">
                  <h2 style="color: #111;">Welcome to your POS workspace</h2>
                  <p>Your tenant <strong>{{ tenant_name }}</strong> has been created and a trial is active.</p>
                  <p>Next steps:</p>
                  <ol>
                    <li>Sign in with your email and password.</li>
                    <li>Complete onboarding: stores, taxes, catalog, and registers.</li>
                  </ol>
                  <p>
                    <a href="/login" style="background:#4f46e5;color:#fff;padding:10px 16px;border-radius:8px;text-decoration:none;">Go to Login</a>
                  </p>
                  <p style="color:#555;">Need help? Reply to this email and we’ll assist.</p>
                </div>
            """,
            "locale": "en",
            "version": 2,
            "is_active": True,
        },
    )


def noop_reverse(apps, schema_editor):
    # leave template as-is on reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_seed_initial_templates"),
    ]

    operations = [
        migrations.RunPython(update_welcome_template, noop_reverse),
    ]
