# Generated by Django 4.2.23 on 2025-12-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Average lead time in days for orders from this vendor', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='safety_stock_days',
            field=models.PositiveIntegerField(blank=True, help_text='Safety stock buffer in days (for reorder calculations)', null=True),
        ),
    ]
