# Generated by Django 4.2.23 on 2025-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_add_vendor_lead_time_safety_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the PO was fully or partially received', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the PO was submitted to the vendor', null=True),
        ),
    ]
