# Generated by Django 4.2.23 on 2025-12-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_add_external_po_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchasing__tenant__688471_idx',
            old_name='purchasing_p_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchasing__tenant__2b3bc1_idx',
            old_name='purchasing_p_tenant__idx2',
        ),
    ]
