# Generated by Django 4.2.23 on 2025-12-05 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0011_add_allow_backorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('ledger', 'Stock Ledger'), ('transfers', 'Transfers'), ('counts', 'Count Sessions'), ('purchase_orders', 'Purchase Orders')], db_index=True, max_length=50)),
                ('last_exported_id', models.BigIntegerField(help_text='Last exported record ID')),
                ('last_exported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('records_exported', models.PositiveIntegerField(default=0, help_text='Number of records in last export')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'export_type'], name='analytics_e_tenant__79c1a9_idx')],
                'unique_together': {('tenant', 'export_type')},
            },
        ),
    ]
