# Generated by Django 4.2.23 on 2025-11-09 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0008_alter_register_tenant'),
        ('tenants', '0002_alter_tenantuser_options'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('void', 'Void')], default='draft', max_length=16)),
                ('return_no', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_returned', models.PositiveIntegerField()),
                ('restock', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('RESALEABLE', 'Resaleable'), ('DAMAGED', 'Damaged'), ('OPEN_BOX', 'Open box')], default='RESALEABLE', max_length=16)),
                ('refund_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.return')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.saleline')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('STORE_CREDIT', 'Store credit'), ('OTHER', 'Other')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('external_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.return')),
            ],
        ),
    ]
