# Generated by Django 4.2.23 on 2025-11-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_return_returnitem_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='reason_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
