# Generated by Django 4.2.23 on 2025-11-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options_customer_address_line1_and_more'),
        ('orders', '0004_returnitem_notes_returnitem_reason_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional customer associated with this sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer'),
        ),
    ]
