# Generated by Django 4.2.23 on 2025-12-05 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_sale_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='disposition',
            field=models.CharField(choices=[('PENDING', 'Pending Inspection'), ('RESTOCK', 'Restock'), ('WASTE', 'Waste')], db_index=True, default='PENDING', help_text='Disposition after inspection: RESTOCK or WASTE', max_length=16),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='inspected_at',
            field=models.DateTimeField(blank=True, help_text='When the inspection was completed', null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='inspected_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_return_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_inspection', 'Awaiting Inspection'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('finalized', 'Finalized'), ('void', 'Void')], db_index=True, default='draft', max_length=20),
        ),
    ]
