# Generated by Django 4.2.23 on 2025-12-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_returnitem_disposition_returnitem_inspected_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['return_ref', 'disposition'], name='orders_retu_return__ca6d16_idx'),
        ),
    ]
