"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# -----------------------------------------------------------------------------
# Core flags & environment
# -----------------------------------------------------------------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "insecure-default")
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"
ALLOWED_HOSTS = [h for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h] or ["localhost", "127.0.0.1"]

# -----------------------------------------------------------------------------
# Installed apps (define first; we'll append 'storages' later if needed)
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "channels",
    # Your apps
    "catalog",
    "orders",
    "inventory",
    "customers",
    "loyalty",
    "stores",
    "payments",
    "tenants",
    "common",
    "analytics",
    "devtools",
    "taxes",
    "discounts",
    "tenant_admin",
    "emails",
    "otp",
    "signup",
    "subscriptions",
    "onboarding",
    "purchasing",
    "webhooks",
]

# -----------------------------------------------------------------------------
# Media (local by default). If S3 is enabled, override below and add app.
# -----------------------------------------------------------------------------
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

USE_S3_MEDIA = os.getenv("USE_S3_MEDIA", "False").lower() == "true"
if USE_S3_MEDIA:
    # Requires: pip install django-storages boto3
    INSTALLED_APPS.append("storages")
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
    AWS_S3_SIGNATURE_VERSION = os.getenv("AWS_S3_SIGNATURE_VERSION", "s3v4")
    # Optional: public-read by default, etc.
    AWS_QUERYSTRING_AUTH = False  # nicer public URLs if bucket policy allows

# -----------------------------------------------------------------------------
# Email (console backend by default; switch to SMTP in prod via env)
# -----------------------------------------------------------------------------
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@example.com")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587")) if os.getenv("EMAIL_PORT") else None
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"

# -----------------------------------------------------------------------------
# Signup / subscriptions defaults
# -----------------------------------------------------------------------------
DEFAULT_SIGNUP_PLAN_CODE = os.getenv("DEFAULT_SIGNUP_PLAN_CODE", "POS_BASIC")
DEFAULT_SIGNUP_TRIAL_DAYS = int(os.getenv("DEFAULT_SIGNUP_TRIAL_DAYS", "14"))

# -----------------------------------------------------------------------------
# OTP rate limits (env-configurable; values are reasonable defaults)
# -----------------------------------------------------------------------------
OTP_RATE_SEND_PER_EMAIL = int(os.getenv("OTP_RATE_SEND_PER_EMAIL", "3"))           # requests per window
OTP_RATE_SEND_EMAIL_WINDOW = int(os.getenv("OTP_RATE_SEND_EMAIL_WINDOW", "300"))  # seconds (5m)
OTP_RATE_SEND_PER_IP = int(os.getenv("OTP_RATE_SEND_PER_IP", "10"))               # requests per window
OTP_RATE_SEND_IP_WINDOW = int(os.getenv("OTP_RATE_SEND_IP_WINDOW", "900"))        # seconds (15m)
OTP_RATE_VERIFY_PER_EMAIL = int(os.getenv("OTP_RATE_VERIFY_PER_EMAIL", "5"))      # attempts per window
OTP_RATE_VERIFY_EMAIL_WINDOW = int(os.getenv("OTP_RATE_VERIFY_EMAIL_WINDOW", "300"))  # seconds (5m)

# Signup rate limits (per email/IP)
SIGNUP_RATE_START_PER_EMAIL = int(os.getenv("SIGNUP_RATE_START_PER_EMAIL", "5"))
SIGNUP_RATE_START_EMAIL_WINDOW = int(os.getenv("SIGNUP_RATE_START_EMAIL_WINDOW", "600"))  # 10m
SIGNUP_RATE_START_PER_IP = int(os.getenv("SIGNUP_RATE_START_PER_IP", "20"))
SIGNUP_RATE_START_IP_WINDOW = int(os.getenv("SIGNUP_RATE_START_IP_WINDOW", "900"))       # 15m
SIGNUP_RATE_VERIFY_PER_EMAIL = int(os.getenv("SIGNUP_RATE_VERIFY_PER_EMAIL", "10"))
SIGNUP_RATE_VERIFY_EMAIL_WINDOW = int(os.getenv("SIGNUP_RATE_VERIFY_EMAIL_WINDOW", "900"))
SIGNUP_RATE_COMPLETE_PER_EMAIL = int(os.getenv("SIGNUP_RATE_COMPLETE_PER_EMAIL", "5"))
SIGNUP_RATE_COMPLETE_EMAIL_WINDOW = int(os.getenv("SIGNUP_RATE_COMPLETE_EMAIL_WINDOW", "900"))

# -----------------------------------------------------------------------------
# REST / JWT
# -----------------------------------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Optional: pagination
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "POS API",
    "VERSION": "1.0.0",
}

# -----------------------------------------------------------------------------
# Channels / Celery
# -----------------------------------------------------------------------------
ASGI_APPLICATION = "core.asgi.application"
REDIS_URL = "redis://localhost:6379/1"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [REDIS_URL]},
    }
}

CELERY_BROKER_URL = "redis://localhost:6379/2"
CELERY_RESULT_BACKEND = "redis://localhost:6379/2"

# -----------------------------------------------------------------------------
# Middleware / Templates / WSGI
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "common.middleware.TenantContextMiddleware",
    "pos.middleware.RegisterSessionMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        # NOTE: you are using DB_* envs; keep them or switch to POSTGRES_* consistently.
        "NAME": os.getenv("DB_NAME", "posdb"),
        "USER": os.getenv("DB_USER", "posuser"),
        "PASSWORD": os.getenv("DB_PASSWORD", "pospass"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "55432"),  # your custom port, keep consistent with Docker/EC2
    }
}

# -----------------------------------------------------------------------------
# Auth validators / i18n / tz
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# Static
# -----------------------------------------------------------------------------
STATIC_ROOT = "/var/www/static"
STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
