# Generated by Django 4.2.23 on 2025-09-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('loyalty_id', models.CharField(blank=True, max_length=64)),
                ('consent_flags', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
