# Generated by Django 4.2.23 on 2025-09-30 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_variant_name'),
        ('stores', '0004_store_is_active'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global (all stores)'), ('STORE', 'Store-specific')], db_index=True, default='GLOBAL', max_length=10)),
                ('basis', models.CharField(choices=[('PCT', 'Percent of line'), ('FLAT', 'Flat fee')], default='PCT', max_length=8)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apply_scope', models.CharField(choices=[('LINE', 'Per line item'), ('RECEIPT', 'Once per receipt')], default='LINE', max_length=10)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='rules', to='catalog.taxcategory')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active', 'scope', 'priority'], name='taxes_taxru_tenant__3b6b7b_idx')],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
