# Generated by Django 4.2.23 on 2025-10-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_alter_taxrule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
