# Generated by Django 4.2.23 on 2025-09-18 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('stores', '0001_initial'),
        ('tenants', '0001_initial'),
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledgerentry',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='inventorytransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorytransfer'),
        ),
        migrations.AddField(
            model_name='inventorytransferline',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='from_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='stores.store'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='to_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='stores.store'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryadjustment'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.adjustmentreason'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='countsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_sessions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countsession',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='countsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='countline',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.countsession'),
        ),
        migrations.AddField(
            model_name='countline',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='adjustmentreason',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['tenant', 'store', 'created_at'], name='inventory_s_tenant__570108_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['tenant', 'variant', 'created_at'], name='inventory_s_tenant__ae5c21_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransferline',
            constraint=models.CheckConstraint(check=models.Q(('qty', 0), _negated=True), name='transfer_line_qty_nonzero'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='inventory_i_tenant__d3257c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('store', 'variant')},
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant', 'store', 'created_at'], name='inventory_i_tenant__3260cb_idx'),
        ),
        migrations.AddIndex(
            model_name='countsession',
            index=models.Index(fields=['tenant', 'store', 'status'], name='inventory_c_tenant__f554ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='countline',
            unique_together={('session', 'variant')},
        ),
        migrations.AddIndex(
            model_name='adjustmentreason',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_a_tenant__e3c072_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adjustmentreason',
            unique_together={('tenant', 'code')},
        ),
    ]
