# Generated by Django 4.2.23 on 2025-09-12 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_options_tenantuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0003_alter_store_postal_code_alter_store_state_and_more'),
        ('catalog', '0003_alter_product_options_product_description_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.adjustmentreason')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryadjustment')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant')),
            ],
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_delta', models.IntegerField()),
                ('balance_after', models.IntegerField(blank=True, null=True)),
                ('ref_type', models.CharField(choices=[('ADJUSTMENT', 'Adjustment'), ('SALE', 'POS Sale'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer'), ('RECEIPT', 'Receipt'), ('COUNT', 'Count')], max_length=20)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'store', 'created_at'], name='inventory_s_tenant__570108_idx'), models.Index(fields=['tenant', 'variant', 'created_at'], name='inventory_s_tenant__ae5c21_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant', 'store', 'created_at'], name='inventory_i_tenant__3260cb_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustmentreason',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_a_tenant__e3c072_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adjustmentreason',
            unique_together={('tenant', 'code')},
        ),
    ]
