# Generated by Django 4.2.23 on 2025-09-13 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_alter_product_options_product_description_and_more'),
        ('stores', '0003_alter_store_postal_code_alter_store_state_and_more'),
        ('tenants', '0002_alter_tenant_options_tenantuser'),
        ('inventory', '0002_adjustmentreason_inventoryadjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorytransfer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventorytransferline',
            constraint=models.CheckConstraint(check=models.Q(('qty', 0), _negated=True), name='transfer_line_qty_nonzero'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='inventory_i_tenant__d3257c_idx'),
        ),
    ]
