# Generated by Django 4.2.23 on 2025-09-15 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_postal_code_alter_store_state_and_more'),
        ('tenants', '0002_alter_tenant_options_tenantuser'),
        ('catalog', '0003_alter_product_options_product_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_inventorytransfer_inventorytransferline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('FINALIZED', 'Finalized')], db_index=True, default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.IntegerField(blank=True, null=True)),
                ('counted_qty', models.IntegerField(default=0)),
                ('method', models.CharField(blank=True, default='SCAN', max_length=12)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('last_scanned_barcode', models.CharField(blank=True, max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.countsession')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variant')),
            ],
        ),
        migrations.AddIndex(
            model_name='countsession',
            index=models.Index(fields=['tenant', 'store', 'status'], name='inventory_c_tenant__f554ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='countline',
            unique_together={('session', 'variant')},
        ),
    ]
