# Generated by Django 4.2.23 on 2025-12-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_counts_v2_scopes_variance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='countsession',
            new_name='inventory_c_tenant__7f8b5f_idx',
            old_name='inventory_co_tenant__idx',
        ),
    ]
