# Generated by Django 4.2.23 on 2025-12-05 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_store_timezone'),
        ('tenants', '0011_add_allow_backorders'),
        ('catalog', '0025_variant_reorder_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_rename_inventory_co_tenant__idx_inventory_c_tenant__7f8b5f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='ref_type',
            field=models.CharField(choices=[('ADJUSTMENT', 'Adjustment'), ('SALE', 'POS Sale'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('RECEIPT', 'Receipt'), ('COUNT', 'Count'), ('COUNT_RECONCILE', 'Count Reconcile'), ('PURCHASE_ORDER_RECEIPT', 'Purchase Order Receipt'), ('WASTE', 'Waste'), ('RESERVATION', 'Reservation'), ('RESERVATION_COMMIT', 'Reservation Commit'), ('RESERVATION_RELEASE', 'Reservation Release')], max_length=30),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(help_text='Reserved quantity')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMMITTED', 'Committed'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('ref_type', models.CharField(help_text='Type of reservation (e.g., POS_CART, WEB_ORDER, MARKETPLACE)', max_length=50)),
                ('ref_id', models.IntegerField(blank=True, help_text='Reference ID (e.g., cart_id, order_id)', null=True)),
                ('channel', models.CharField(default='POS', help_text='Channel identifier (POS, WEB, MARKETPLACE, etc.)', max_length=50)),
                ('note', models.TextField(blank=True, help_text='Optional note about the reservation')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time for the reservation', null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'store', 'status'], name='inventory_r_tenant__f113af_idx'), models.Index(fields=['tenant', 'variant', 'status'], name='inventory_r_tenant__cf7aca_idx'), models.Index(fields=['ref_type', 'ref_id'], name='inventory_r_ref_typ_91ce76_idx'), models.Index(fields=['status', 'expires_at'], name='inventory_r_status_8d1db9_idx')],
            },
        ),
    ]
