# Generated by Django 4.2.23 on 2025-12-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_extensions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='icdcinvoice',
            new_name='domain_exte_tenant__6406af_idx',
            old_name='icdc_invoice_tenant_icdc_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcinvoice',
            new_name='domain_exte_tenant__403ec2_idx',
            old_name='icdc_invoice_tenant_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcinvoice',
            new_name='domain_exte_tenant__6f50f0_idx',
            old_name='icdc_invoice_tenant_store_status_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcinvoice',
            new_name='domain_exte_invoice_3ba32a_idx',
            old_name='icdc_invoice_date_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcinvoice',
            new_name='domain_exte_receive_b31dc7_idx',
            old_name='icdc_invoice_received_at_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcinvoiceline',
            new_name='domain_exte_invoice_1ee821_idx',
            old_name='icdc_line_invoice_line_number_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcinvoiceline',
            new_name='domain_exte_invoice_6dd25f_idx',
            old_name='icdc_line_invoice_product_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcinvoiceline',
            new_name='domain_exte_invoice_182f14_idx',
            old_name='icdc_line_invoice_variant_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcinvoiceline',
            new_name='domain_exte_brand_n_d0da57_idx',
            old_name='icdc_line_brand_number_idx',
        ),
        migrations.AlterField(
            model_name='icdcinvoiceline',
            name='has_discrepancy',
            field=models.BooleanField(default=False, help_text="True if there's a calculation discrepancy"),
        ),
    ]
