# Generated by Django 4.2.23 on 2025-10-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'ordering': ['id']},
        ),
    ]
