# Generated by Django 4.2.23 on 2025-11-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_currency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='additional_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_license_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_postal_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ein',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gst_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pan_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state_tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tan_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('gst_number__isnull', True), _negated=True), models.Q(('gst_number', ''), _negated=True)), fields=('gst_number',), name='uniq_tenant_gst_number'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('pan_number__isnull', True), _negated=True), models.Q(('pan_number', ''), _negated=True)), fields=('pan_number',), name='uniq_tenant_pan_number'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('tan_id__isnull', True), _negated=True), models.Q(('tan_id', ''), _negated=True)), fields=('tan_id',), name='uniq_tenant_tan_id'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('ein__isnull', True), _negated=True), models.Q(('ein', ''), _negated=True)), fields=('ein',), name='uniq_tenant_ein'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('state_tax_id__isnull', True), _negated=True), models.Q(('state_tax_id', ''), _negated=True)), fields=('state_tax_id',), name='uniq_tenant_state_tax_id'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('business_license_number__isnull', True), _negated=True), models.Q(('business_license_number', ''), _negated=True)), fields=('business_license_number',), name='uniq_tenant_business_license_number'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('email__isnull', True), _negated=True), models.Q(('email', ''), _negated=True)), fields=('email',), name='uniq_tenant_email'),
        ),
    ]
