# Generated by Django 4.2.23 on 2025-11-24 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenant_additional_details_tenant_business_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=160)),
                ('doc_type', models.CharField(blank=True, help_text='Optional tag like LICENSE, GST, PAN, OTHER', max_length=80)),
                ('file', models.FileField(upload_to=tenants.models.tenant_doc_upload_path)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant document',
                'verbose_name_plural': 'Tenant documents',
                'ordering': ['-created_at', 'label'],
                'indexes': [models.Index(fields=['tenant', 'doc_type'], name='tenants_ten_tenant__a057a5_idx'), models.Index(fields=['tenant', 'label'], name='tenants_ten_tenant__624558_idx')],
            },
        ),
    ]
