# Generated by Django 4.2.23 on 2025-11-24 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdoc',
            name='subject_user',
            field=models.ForeignKey(blank=True, help_text='Optional: tie this doc to a specific person in the tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='id_document_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('DRIVER_LICENSE', "Driver's License"), ('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('SSN', 'SSN'), ('NATIONAL_ID', 'National ID'), ('OTHER', 'Other')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='tenantdoc',
            index=models.Index(fields=['tenant', 'subject_user'], name='tenants_ten_tenant__5949e5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'last_name'], name='tenants_ten_tenant__e2e049_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'personal_phone'], name='tenants_ten_tenant__89819a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'personal_email'], name='tenants_ten_tenant__c5e809_idx'),
        ),
    ]
