# Generated by Django 4.2.23 on 2025-11-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenantdoc_subject_user_tenantuser_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('basic_profile', 'Basic profile complete'), ('store_setup', 'Store setup'), ('live', 'Live')], default='not_started', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='signup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
