# Generated by Django 4.2.23 on 2025-11-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenant_onboarding_status_tenant_signup_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
