# Generated by Django 4.2.23 on 2025-12-02 18:08

from django.db import migrations, models
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_country_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.tenant_logo_upload_path),
        ),
    ]
