# Generated by Django 4.2.23 on 2025-12-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_add_tenant_logo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_reorder_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
