# Generated by Django 4.2.23 on 2025-12-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_default_reorder_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_backorders',
            field=models.BooleanField(default=False, help_text='Allow reservations to exceed on_hand quantity'),
        ),
    ]
