# Generated by Django 4.2.23 on 2025-12-10 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0011_add_allow_backorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdoc',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp', null=True),
        ),
        migrations.AddField(
            model_name='tenantdoc',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tenant_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tenantdoc',
            index=models.Index(fields=['tenant', 'deleted_at'], name='tenants_ten_tenant__2e9e6b_idx'),
        ),
    ]
