# Generated by Django 4.2.23 on 2025-11-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, help_text='ISO alpha-2; leave blank for global default', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('send_per_email', models.PositiveIntegerField(default=3)),
                ('send_email_window', models.PositiveIntegerField(default=300, help_text='Seconds')),
                ('send_per_ip', models.PositiveIntegerField(default=10)),
                ('send_ip_window', models.PositiveIntegerField(default=900, help_text='Seconds')),
                ('verify_per_email', models.PositiveIntegerField(default=5)),
                ('verify_email_window', models.PositiveIntegerField(default=300, help_text='Seconds')),
            ],
            options={
                'ordering': ['country_code'],
                'unique_together': {('country_code', 'is_active')},
            },
        ),
    ]
