# Generated by Django 4.2.23 on 2025-11-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0002_otpconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("purpose", models.CharField(max_length=32)),
                ("action", models.CharField(choices=[("verify_failed", "Verify failed")], max_length=32)),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="otpaudit",
            index=models.Index(fields=["email", "purpose"], name="otp_otpaudi_email_e55e26_idx"),
        ),
        migrations.AddIndex(
            model_name="otpaudit",
            index=models.Index(fields=["action"], name="otp_otpaudi_action_17fe33_idx"),
        ),
    ]
