# Generated by Django 4.2.23 on 2025-12-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_otpaudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpaudit',
            new_name='otp_otpaudi_email_dfbc1b_idx',
            old_name='otp_otpaudi_email_e55e26_idx',
        ),
        migrations.RenameIndex(
            model_name='otpaudit',
            new_name='otp_otpaudi_action_170d0f_idx',
            old_name='otp_otpaudi_action_17fe33_idx',
        ),
    ]
