# Generated by Django 4.2.23 on 2025-09-30 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0004_store_is_active'),
        ('tenants', '0001_initial'),
        ('catalog', '0004_variant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('STORE', 'Store-specific')], db_index=True, default='GLOBAL', max_length=10)),
                ('basis', models.CharField(choices=[('PCT', 'Percent'), ('FLAT', 'Flat amount')], default='PCT', max_length=8)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apply_scope', models.CharField(choices=[('LINE', 'Per line'), ('RECEIPT', 'Per receipt')], default='LINE', max_length=10)),
                ('target', models.CharField(choices=[('ALL', 'All items'), ('CATEGORY', 'Tax categories'), ('PRODUCT', 'Specific products'), ('VARIANT', 'Specific variants')], default='ALL', max_length=10)),
                ('stackable', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='discount_rules', to='catalog.taxcategory')),
                ('products', models.ManyToManyField(blank=True, related_name='discount_rules', to='catalog.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('variants', models.ManyToManyField(blank=True, related_name='discount_rules', to='catalog.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('min_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discountrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['tenant', 'is_active', 'scope', 'priority'], name='discounts_d_tenant__2830ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discountrule',
            unique_together={('tenant', 'code')},
        ),
    ]
