# Generated by Django 4.2.23 on 2025-10-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['code', 'id']},
        ),
        migrations.AlterModelOptions(
            name='discountrule',
            options={'ordering': ['priority', 'id']},
        ),
    ]
