# Generated by Django 4.2.23 on 2025-10-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_alter_coupon_options_alter_discountrule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountrule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
