# Generated by Django 4.2.23 on 2025-10-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_discountrule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
