# Generated by Django 4.2.23 on 2025-11-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allowed_country_codes',
            field=models.JSONField(blank=True, default=list, help_text='If set, restrict to these countries (ISO alpha-2)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_plan_codes',
            field=models.JSONField(blank=True, default=list, help_text='If set, restrict to these plan codes'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_signup_only',
            field=models.BooleanField(default=False, help_text='Limit usage to signup/subscription flow'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_tenant_limit',
            field=models.PositiveIntegerField(default=1, help_text='Max times a single tenant can redeem'),
        ),
    ]
