# Generated by Django 4.2.23 on 2025-08-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('psp_token', models.CharField(blank=True, max_length=128)),
                ('approval_code', models.CharField(blank=True, max_length=32)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
