# Generated by Django 4.2.23 on 2025-09-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('psp_token', models.CharField(blank=True, max_length=128)),
                ('approval_code', models.CharField(blank=True, max_length=32)),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_auth_code', models.CharField(blank=True, max_length=32, null=True)),
                ('card_reference', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.sale')),
            ],
        ),
    ]
