# Generated by Django 4.2.23 on 2025-09-18 02:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.taxcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['tenant', 'is_active'], name='catalog_var_tenant__e32355_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'is_active'], name='catalog_var_product_4064cc_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(django.db.models.functions.text.Lower('sku'), name='variant_sku_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(django.db.models.functions.text.Lower('barcode'), name='variant_barcode_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='uniq_variant_sku_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__gt', '')), fields=('tenant', 'barcode'), name='uniq_variant_barcode_per_tenant_when_present'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'sku')},
        ),
        migrations.AddIndex(
            model_name='taxcategory',
            index=models.Index(fields=['tenant', 'code'], name='catalog_tax_tenant__8033bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxcategory',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'name'], name='catalog_pro_tenant__750d04_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='catalog_pro_tenant__e1f8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category'], name='catalog_pro_tenant__ab737f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'code'], name='catalog_pro_tenant__94eca2_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'name'], name='catalog_cat_tenant__eba91e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'code'], name='catalog_cat_tenant__2b319f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'name')},
        ),
    ]
