# Generated by Django 4.2.23 on 2025-09-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxcategory',
            options={'verbose_name': 'Tax category', 'verbose_name_plural': 'Tax categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
