# Generated by Django 4.2.23 on 2025-09-18 21:43

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_path),
        ),
        migrations.AddField(
            model_name='variant',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.variant_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
