# Generated by Django 4.2.23 on 2025-09-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image_file_variant_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='name',
            field=models.CharField(db_index=True, default='TEST', max_length=64),
            preserve_default=False,
        ),
    ]
