# Generated by Django 4.2.23 on 2025-10-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_variant_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxcategory',
            options={'ordering': ['code', 'id'], 'verbose_name': 'Tax category', 'verbose_name_plural': 'Tax categories'},
        ),
    ]
