# Generated by Django 4.2.23 on 2025-10-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_taxcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
