# Generated by Django 4.2.23 on 2025-10-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_taxcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
