# Generated by Django 4.2.23 on 2025-10-29 21:23

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_uniq_product_code_per_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_code_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='variant',
            name='uniq_variant_sku_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='variant',
            name='uniq_variant_name_per_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('tenant'), name='uniq_product_code_ci_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('code', ''), _negated=True), name='product_code_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), models.F('tenant'), name='uniq_variant_sku_ci_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('product'), name='uniq_variant_name_ci_per_product'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='variant_name_not_blank'),
        ),
    ]
