# Generated by Django 4.2.23 on 2025-11-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_product_uniq_product_code_per_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="margin_percentage",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
