# Generated by Django 4.2.23 on 2025-12-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_variant_margin_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='reorder_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
