# Generated by Django 4.2.23 on 2025-11-20 19:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_options_customer_address_line1_and_more'),
        ('tenants', '0002_alter_tenantuser_options'),
        ('orders', '0005_sale_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0)),
                ('tier', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('earn_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Points earned per 1.00 of currency spent.', max_digits=6)),
                ('redeem_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Points needed per 1.00 of currency redeemed (store credit).', max_digits=6)),
                ('tiers', models.JSONField(blank=True, help_text='Optional tier rules (e.g. thresholds for Silver/Gold/etc.)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem'), ('ADJUST', 'Adjust')], max_length=16)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'type'], name='loyalty_loy_tenant__bcefb7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['tenant', 'points_balance'], name='loyalty_loy_tenant__f95a5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loyaltyaccount',
            unique_together={('tenant', 'customer')},
        ),
    ]
