# Generated by Django 4.2.23 on 2025-11-23 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
