# Generated by Django 4.2.23 on 2025-11-25
from django.db import migrations
from django.utils import timezone


def seed_plans(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    PlanPrice = apps.get_model("subscriptions", "PlanPrice")

    plan, _ = Plan.objects.update_or_create(
        code="POS_BASIC",
        defaults={
            "name": "POS Basic",
            "description": "Starter plan with trial",
            "is_active": True,
            "trial_days": 14,
            "max_stores": 1,
            "max_users": 3,
            "max_registers": 3,
            "features": {"analytics": "basic", "support": "email"},
        },
    )

    for currency, amount in [("USD", 29.00), ("INR", 999.00)]:
        PlanPrice.objects.update_or_create(
            plan=plan,
            currency=currency,
            billing_period="monthly",
            country_code="",
            version=1,
            defaults={
                "amount": amount,
                "valid_from": timezone.now(),
                "valid_to": None,
            },
        )


def unseed_plans(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    PlanPrice = apps.get_model("subscriptions", "PlanPrice")
    PlanPrice.objects.filter(plan__code="POS_BASIC").delete()
    Plan.objects.filter(code="POS_BASIC").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_plans, unseed_plans),
    ]
