# Generated by Django 4.2.23 on 2025-11-25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_seed_default_planprice"),
    ]

    operations = [
        # Use RunSQL to conditionally add the column only if it doesn't exist
        # This handles the case where the column was already created in 0001_initial
        # The column was included in 0001_initial, so this migration is effectively a no-op
        # but we keep it for migration dependency chain integrity
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='subscriptions_plan' AND column_name='trial_days'
                    ) THEN
                        ALTER TABLE subscriptions_plan 
                        ADD COLUMN trial_days INTEGER DEFAULT 14 NOT NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE subscriptions_plan DROP COLUMN IF EXISTS trial_days;
            """
        ),
    ]
