# Generated by Django 4.2.23 on 2025-11-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0005_coupon_allowed_country_codes_and_more"),
        ("subscriptions", "0003_add_plan_trial_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="coupon",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="discounts.coupon",
            ),
        ),
    ]
