# Generated by Django 4.2.23 on 2025-11-27

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0004_subscription_coupon_fk"),
        ("tenants", "0008_tenant_country_default_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("created", "Created"), ("status_changed", "Status changed"), ("amount_changed", "Amount changed"), ("auto_renew_changed", "Auto-renew changed")], max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="subscriptions.subscription"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscription_audits", to="tenants.tenant"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriptionaudit",
            index=models.Index(fields=["subscription", "action"], name="subscriptio_subscri_0882c5_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriptionaudit",
            index=models.Index(fields=["tenant"], name="subscriptio_tenant__2e2111_idx"),
        ),
    ]
