# Generated by Django 4.2.23 on 2025-12-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptionaudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscriptionaudit',
            new_name='subscriptio_subscri_74c701_idx',
            old_name='subscriptio_subscri_0882c5_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionaudit',
            new_name='subscriptio_tenant__cce790_idx',
            old_name='subscriptio_tenant__2e2111_idx',
        ),
    ]
