# Generated by Django 4.2.23 on 2025-08-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.AddField(
            model_name='store',
            name='address_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(db_index=True, default='TEST', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(db_index=True, default='USA', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
