# Generated by Django 4.2.23 on 2025-08-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_address_store_address_meta_store_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='postal_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='street',
            field=models.CharField(max_length=200),
        ),
    ]
