# Generated by Django 4.2.23 on 2025-09-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_register_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
