# Generated by Django 4.2.23 on 2025-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['code', 'id']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['code', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['tenant', 'code'], name='stores_stor_tenant__07bfdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_store_code_per_tenant'),
        ),
    ]
