# Generated by Django 4.2.23 on 2025-10-17 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantuser_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0005_alter_register_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='register',
            name='access_pin_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['store', 'code'], name='stores_regi_store_i_b23448_idx'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['is_active', 'store'], name='stores_regi_is_acti_457461_idx'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['locked_until'], name='stores_regi_locked__78760f_idx'),
        ),
        migrations.AddField(
            model_name='registersession',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_register_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registersession',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stores.register'),
        ),
        migrations.AddField(
            model_name='registersession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_sessions', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='registersession',
            index=models.Index(fields=['tenant', 'register'], name='stores_regi_tenant__204b77_idx'),
        ),
        migrations.AddIndex(
            model_name='registersession',
            index=models.Index(fields=['expires_at'], name='stores_regi_expires_c6e701_idx'),
        ),
        migrations.AddIndex(
            model_name='registersession',
            index=models.Index(fields=['revoked_at'], name='stores_regi_revoked_7d134c_idx'),
        ),
    ]
