# Generated by Django 4.2.23 on 2025-10-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantuser_options'),
        ('stores', '0006_registersession_register_access_pin_hash_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='register',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['tenant', 'code'], name='stores_regi_tenant__77cb2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_register_code_per_tenant'),
        ),
    ]
