# Generated by Django 4.2.23 on 2025-10-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantuser_options'),
        ('stores', '0007_alter_register_unique_together_register_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
            preserve_default=False,
        ),
    ]
