# Generated by Django 4.2.23 on 2025-11-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_closing_time_store_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
